server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: SSO
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}test-client"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080"
              scopes:
                - "test"
            require-authorization-consent: false
          token:
            access-token-time-to-live: 3600000