server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: SSO
  datasource:
    url: ${DATASOURCE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "gooseGame-client"
              client-secret: ${CLIENT_SECRET}
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - ${REDIRECT_URL}
              scopes:
                - "read"
            require-authorization-consent: false
          token:
            access-token-time-to-live: 3600000