version: '3.8'

services: 

  game:
    image: postgres
    environment: 
      POSTGRES_DB: game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - app-volume:/var/lib/postgresql/data

  users:
    image: postgres
    environment: 
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    # Notice I don't even use a volume here since I don't care to persist test data between runs

volumes:
  app-volume: #
