server:
  port: 8081

spring:
  application:
    name: goosegamebackend
  datasource:
    hikari:
      maximum-pool-size: 5
    url: ${DATASOURCE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

app:
  goose-update-timing: 60
  item-add-timing: 360
